Delete Account and Project
Wolox/metrics-account-management-react pull request #18
Opened 2020-08-26 13:04 UTC by oliferwolox

## Summary

Add delete modal.

## Screenshots

[Change!] Show the screenshots of the views you modified.

2020-09-02 20:01 UTC, BJordi requested changes

2020-09-03 12:32 UTC, oliferwolox commented on src/app/screens/AccountDetail/index.tsx
> +                    {...project}
i need it to be before the accountId prop to overwrite it

2020-09-09 14:26 UTC, BJordi approved these changes

2020-09-09 14:26 UTC, BJordi commented on src/app/components/Modals/DeletionModal/index.tsx
> +        <button type="button" className={cn('secondary-button', styles.cancelButton)} onClick={onClose}>
Maybe we should standardize the names of the methods. Here it's `onClose` and on line 43 we have `handleDelete`. Handle or on?

2020-09-16 14:13 UTC, merged